import { Employee } from '../src/Store/Employees';

export const mockedDatas: Employee[] = [
	{
		firstName: "Robert",
		lastName: "Chang",
		birthDate: "25/06/1995",
		startDay: "12/08/2019",
		street: "9 Pigalle street",
		city: "Houston",
		state: "Texas",
		zipcode: 25550,
		department: "Human Ressources",
	},
	{
		firstName: "Jason",
		lastName: "Flores",
		birthDate: "07/05/1994",
		startDay: "13/05/2019",
		street: "12 Down street",
		city: "Atlanta",
		state: "Georgia",
		zipcode: 49960,
		department: "Marketing",
	},
	{
		firstName: "Pablo",
		lastName: "Camara",
		birthDate: "23/12/1999",
		startDay: "05/01/2014",
		street: "Palace Place",
		city: "Cleveland",
		state: "Ohio",
		zipcode: 68550,
		department: "Sales",
	},
	{
		firstName: "Mohamed",
		lastName: "Dupont",
		birthDate: "02/03/1990",
		startDay: "02/06/2020",
		street: "15 Broke street",
		city: "South Park",
		state: "Colorado",
		zipcode: 38500,
		department: "Sales",
	},
	{
		firstName: "Michel",
		lastName: "Delgado",
		birthDate: "01/11/2001",
		startDay: "10/08/2020",
		street: "256 Pirate street",
		city: "Memphis",
		state: "Alabama",
		zipcode: 49900,
		department: "Engineering",
	},
	{
		firstName: "Olivia",
		lastName: "Delorenzo",
		birthDate: "25/04/1995",
		startDay: "01/05/2017",
		street: "3 Anemones street",
		city: "Orlando",
		state: "Florida",
		zipcode: 69600,
		department: "Legal",
	},
	{
		firstName: "Jean-Luc",
		lastName: "Bowie",
		birthDate: "24/05/1994",
		startDay: "30/09/2021",
		street: "996 Dropped street",
		city: "Boston",
		state: "Massachussets",
		zipcode: 87550,
		department: "Marketing",
	},
	{
		firstName: "Eric",
		lastName: "De la Vega",
		birthDate: "03/05/1961",
		startDay: "07/08/2014",
		street: "56 Napoleon Street",
		city: "Detroit",
		state: "Michigan",
		zipcode: 35610,
		department: "Human Ressources",
	},
	{
		firstName: "Patricia",
		lastName: "Polizzi",
		birthDate: "05/07/1965",
		startDay: "08/08/2015",
		street: "123 Patrick Swaize street",
		city: "Dallas",
		state: "Nevada",
		zipcode: 15300,
		department: "Human Ressources",
	},
	{
		firstName: "Chrystel",
		lastName: "Hanks",
		birthDate: "04/08/1984",
		startDay: "12/01/2011",
		street: "330 Bird street",
		city: "Houston",
		state: "Texas",
		zipcode: 48900,
		department: "Legal",
	},
	{
		firstName: "Thomas",
		lastName: "Rotschild",
		birthDate: "01/11/1987",
		startDay: "11/02/2012",
		street: "87 Space street",
		city: "Point Place",
		state: "Wisconsin",
		zipcode: 19870,
		department: "Engineering",
	},
]

// export default mockedDatas;