export interface americanState {
	value: string;
	label: string;
}

export  const americanStates:americanState[] = [
  { value: 'alabama', label: 'Alabama' },
  { value: 'alaska', label: 'Alaska' },
  { value: 'american Samoa', label: 'American Samoa' },
  { value: 'arizona', label: 'Arizona' },
  { value: 'arkansas', label: 'Arkansas' },
  { value: 'california', label: 'California' },
  { value: 'colorado', label: 'Colorado' },
  { value: 'connecticut', label: 'Connecticut' },
  { value: 'delaware', label: 'Delaware' },
  { value: 'district of colombia', label: 'District of Colombia' },
  { value: 'federated states of micronesia', label: 'Federated States of Micronesia' },
  { value: 'florida', label: 'Florida' },
  { value: 'georgia', label: 'Georgia' },
  { value: 'guam', label: 'Guam' },
  { value: 'hawaii', label: 'Hawaii' },
  { value: 'idaho', label: 'Idaho' },
  { value: 'illinois', label: 'Illinois' },
  { value: 'indiana', label: 'Indiana' },
  { value: 'iowa', label: 'Iowa' },
  { value: 'kansas', label: 'Kansas' },
  { value: 'kentucky', label: 'Kentucky' },
  { value: 'louisiana', label: 'Strawberry' },
  { value: 'maine', label: 'Maine' },
  { value: 'marshall Islands', label: 'Marshall Islands' },
  { value: 'maryland', label: 'Maryland' },
  { value: 'massachussets', label: 'Massachussets' },
  { value: 'michigan', label: 'Michigan' },
  { value: 'minnesota', label: 'Minnesota' },
  { value: 'mississippi', label: 'Mississippi' },
  { value: 'missouri', label: 'Missouri' },
  { value: 'montana', label: 'Montana' },
  { value: 'nebraska', label: 'Nebraska' },
  { value: 'nevada', label: 'Nevada' },
  { value: 'new Hampshire', label: 'New Hampshire' },
  { value: 'new Jersey', label: 'New Jersey' },
  { value: 'new Mexico', label: 'New Mexico' },
  { value: 'new York', label: 'New York' },
  { value: 'north Carolina', label: 'North Carolina' },
  { value: 'north Dakota', label: 'North Dakota' },
  { value: 'northern mariana islands', label: 'Northern Mariana Islands' },
  { value: 'ohio', label: 'Ohio' },
  { value: 'oklahoma', label: 'Oklahoma' },
  { value: 'oregon', label: 'Oregon' },
  { value: 'palau', label: 'Palau' },
  { value: 'pennsylvania', label: 'Pennsylvania' },
  { value: 'puerto Rico', label: 'Puerto Rico' },
  { value: 'rhode Islands', label: 'Rhode Islands' },
  { value: 'south Carolina', label: 'South Carolina' },
  { value: 'south Dakota', label: 'South Dakota' },
  { value: 'tennessee', label: 'Tennessee' },
  { value: 'texas', label: 'Texas' },
  { value: 'utah', label: 'Utah' },
  { value: 'vermont', label: 'Vermont' },
  { value: 'virgin islands', label: 'Virgin Islands' },
  { value: 'virginia', label: 'Virginia' },
  { value: 'washington', label: 'Washington' },
  { value: 'west virginia', label: 'West Virginia' },
  { value: 'wisconsin', label: 'Wisconsin' },
  { value: 'wyoming', label: 'Wyoming' }
]


// export default americanStates;